---
# - name: Django | Create application user and home.
#   user: >
#     home={{project.root}}
#     name={{project.user}}
#     generate_ssh_key: yes
#     ssh_key_bits: 2048
#     ssh_key_file: .ssh/id_rsa
#     groups=www-data
#     state=present
#   tags:
#     - base
#     - user
#     - provision
#     - app

# - name: Django | Ssh | Change permissions
#   sudo: true
#   shell: chown -R {{project.user}}:{{project.user}} {{project.root}} -R
#   tags:
#     - base
#     - user
#     - provision
#     - app
