---
- name: uWSGI | (apt) Install required system packages.
  become: yes
  become_user: root
  apt: >
    pkg={{item}}
    state=installed
    update-cache=yes
  with_items:
    - build-essential
    - python3-dev
    - python3-setuptools
    - python3-psycopg2
    - python3-pip
  tags:
    - packages
    - provision

- name: uWSGI | (pip) Install required system packages.
  become: yes
  become_user: root
  pip: name={{item}} executable=pip3.6
  with_items:
    - uwsgi
  tags:
    - packages
    - provision

