---
- name: uWSGI | Install uwsgi systemd job.
  notify: restart uwsgi
  template: >
    src=systemd.uwsgi.service.j2
    dest=/etc/systemd/system/uwsgi.service
    owner=root
    group=root
    mode=0644
  tags:
    - configuration
    - uwsgi
    - appserver
    - update

- name: uWSGI | Start daemon and enable it for system startup
  systemd: >
    name=uwsgi
    state=started
    enabled=yes
    daemon_reload=yes
  tags:
    - uwsgi
